#pragma once

/// GENERATION SETTINGS ///
#define NUM_CHUNKS_TYPE 5
#define CHUNKS_AHEAD 3

// GAME FEEL SETTINGS
#define BOBBING_INTENSITY 0.025f

// GAMEPLAY SETTINGS
#define VEHICLE_MIN_SPEED 0.1f
#define VEHICLE_MAX_SPEED 3.0f
#define ENEMY_SPAWN_CHANCE 40 // In %